<script setup lang="ts">
import { computed } from 'vue'
import { Trash2, ChevronDown } from 'lucide-vue-next'
import type { CardItem, MultiStepElement, RangeUnit } from '../../../stores/multistepForm'
import FieldGroup from './FieldGroup.vue'

const props = defineProps<{ element: MultiStepElement }>()
const emit = defineEmits<{ update: [patch: Partial<MultiStepElement>] }>()

const showsPlaceholder = computed(() =>
  ['text', 'textarea', 'email', 'phone', 'number', 'password'].includes(props.element.type)
)
const isOptionsKind = computed(() =>
  props.element.type === 'select' || props.element.type === 'radio'
)
const isRow = computed(() => props.element.type === 'row')
const isStepper = computed(() => props.element.type === 'stepper')
const isDateRange = computed(() => props.element.type === 'daterange')
const isCardsKind = computed(
  () => props.element.type === 'radiocards' || props.element.type === 'checkboxcards',
)

const RANGE_UNITS: RangeUnit[] = ['nights', 'days', 'hours', 'weeks']

function updateOption(i: number, value: string) {
  const next = [...(props.element.options ?? [])]
  next[i] = value
  emit('update', { options: next })
}

function removeOption(i: number) {
  const next = [...(props.element.options ?? [])]
  next.splice(i, 1)
  emit('update', { options: next })
}

function addOption() {
  const list = props.element.options ?? []
  emit('update', { options: [...list, `Option ${list.length + 1}`] })
}

function slugify(input: string): string {
  return input
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '') || 'option'
}

function patchCard(i: number, patch: Partial<CardItem>) {
  const next = [...(props.element.cards ?? [])]
  if (!next[i]) return
  const merged: CardItem = { ...next[i], ...patch }
  // If the title changed and the value still looks autogenerated from the old title,
  // re-derive it. Authors can override `value` directly via the dedicated input.
  if (patch.title !== undefined && next[i].value === slugify(next[i].title)) {
    merged.value = slugify(merged.title)
  }
  next[i] = merged
  emit('update', { cards: next })
}

function removeCard(i: number) {
  const next = [...(props.element.cards ?? [])]
  next.splice(i, 1)
  emit('update', { cards: next })
}

function addCard() {
  const list = props.element.cards ?? []
  const idx = list.length + 1
  emit('update', {
    cards: [
      ...list,
      { value: `option-${idx}`, title: `Option ${idx}` },
    ],
  })
}

function patchNumber(field: 'min' | 'max' | 'step' | 'defaultValue', raw: string) {
  if (raw === '') {
    emit('update', { [field]: undefined } as Partial<MultiStepElement>)
    return
  }
  const num = Number(raw)
  if (!Number.isFinite(num)) return
  emit('update', { [field]: num } as Partial<MultiStepElement>)
}
</script>

<template>
  <div :key="element.id" class="space-y-5 ms-fade-up">
    <FieldGroup label="Label">
      <input
        :value="element.label"
        @input="emit('update', { label: ($event.target as HTMLInputElement).value })"
        class="w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-2 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
      />
    </FieldGroup>

    <FieldGroup v-if="showsPlaceholder" label="Placeholder">
      <input
        :value="element.placeholder ?? ''"
        @input="emit('update', { placeholder: ($event.target as HTMLInputElement).value })"
        class="w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-2 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
      />
    </FieldGroup>

    <label
      v-if="!isRow"
      class="flex items-center gap-3 p-3 border border-slate-200 dark:border-white/[0.07] rounded-lg cursor-pointer hover:bg-slate-50 dark:hover:bg-white/[0.04]"
    >
      <input
        type="checkbox"
        :checked="!!element.required"
        @change="emit('update', { required: ($event.target as HTMLInputElement).checked })"
        class="h-4 w-4 text-indigo-600 rounded border-slate-300 dark:border-white/20 bg-white dark:bg-transparent"
      />
      <span class="text-sm font-medium text-slate-700 dark:text-white/75">Required field</span>
    </label>

    <p
      v-if="isRow"
      class="text-[12px] text-slate-500 dark:text-white/40 leading-relaxed"
    >
      Drag fields from the sidebar into this row to lay them out side by side.
    </p>

    <FieldGroup v-if="isStepper" label="Stepper">
      <div class="grid grid-cols-2 gap-2">
        <label class="block">
          <span class="text-[11px] font-medium text-slate-500 dark:text-white/50 uppercase tracking-wider">Min</span>
          <input
            type="number"
            :value="element.min ?? ''"
            @input="patchNumber('min', ($event.target as HTMLInputElement).value)"
            class="mt-1 w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
        </label>
        <label class="block">
          <span class="text-[11px] font-medium text-slate-500 dark:text-white/50 uppercase tracking-wider">Max</span>
          <input
            type="number"
            :value="element.max ?? ''"
            @input="patchNumber('max', ($event.target as HTMLInputElement).value)"
            class="mt-1 w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
        </label>
        <label class="block">
          <span class="text-[11px] font-medium text-slate-500 dark:text-white/50 uppercase tracking-wider">Step</span>
          <input
            type="number"
            min="0"
            :value="element.step ?? ''"
            @input="patchNumber('step', ($event.target as HTMLInputElement).value)"
            class="mt-1 w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
        </label>
        <label class="block">
          <span class="text-[11px] font-medium text-slate-500 dark:text-white/50 uppercase tracking-wider">Default</span>
          <input
            type="number"
            :value="element.defaultValue ?? ''"
            @input="patchNumber('defaultValue', ($event.target as HTMLInputElement).value)"
            class="mt-1 w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
        </label>
      </div>
    </FieldGroup>

    <FieldGroup v-if="isDateRange" label="Range unit">
      <select
        :value="element.rangeUnit ?? 'days'"
        @change="emit('update', { rangeUnit: ($event.target as HTMLSelectElement).value as RangeUnit })"
        class="w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-2 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none appearance-none"
      >
        <option v-for="u in RANGE_UNITS" :key="u" :value="u">{{ u }}</option>
      </select>
      <p class="mt-1.5 text-[11px] text-slate-500 dark:text-white/40 leading-relaxed">
        Determines how the gap between dates is summarised under the field (e.g. "3 nights").
      </p>
    </FieldGroup>

    <FieldGroup v-if="isCardsKind" label="Cards">
      <div class="space-y-3">
        <div
          v-for="(card, i) in element.cards ?? []"
          :key="i"
          class="space-y-1.5 p-3 rounded-lg border border-slate-200 dark:border-white/[0.07] bg-slate-50/60 dark:bg-white/[0.02]"
        >
          <div class="flex items-start gap-2">
            <input
              :value="card.title"
              @input="patchCard(i, { title: ($event.target as HTMLInputElement).value })"
              placeholder="Title"
              class="flex-1 min-w-0 border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-sm font-semibold text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
            />
            <button
              type="button"
              @click="removeCard(i)"
              class="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:text-white/40 dark:hover:text-rose-400 dark:hover:bg-rose-500/10 rounded-lg shrink-0"
              :aria-label="'Remove card ' + (i + 1)"
            >
              <Trash2 class="h-3.5 w-3.5" />
            </button>
          </div>
          <input
            :value="card.description ?? ''"
            @input="patchCard(i, { description: ($event.target as HTMLInputElement).value })"
            placeholder="Description (optional)"
            class="w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-[12px] text-slate-700 dark:text-white/80 bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
          <input
            :value="card.meta ?? ''"
            @input="patchCard(i, { meta: ($event.target as HTMLInputElement).value })"
            placeholder="Meta — e.g. €285 / night"
            class="w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-[12px] text-slate-700 dark:text-white/80 bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
          <input
            :value="card.value"
            @input="patchCard(i, { value: ($event.target as HTMLInputElement).value })"
            placeholder="value"
            class="w-full border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1 text-[11px] font-mono text-slate-500 dark:text-white/50 bg-transparent focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
        </div>
        <button
          type="button"
          @click="addCard"
          class="w-full py-1.5 text-[12px] font-medium text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 dark:hover:bg-indigo-500/20 rounded-lg transition-colors"
          style="transition-timing-function: cubic-bezier(0.16, 1, 0.3, 1)"
        >
          + Add card
        </button>
      </div>
    </FieldGroup>

    <FieldGroup v-if="isOptionsKind" label="Options">
      <div class="space-y-1.5">
        <div
          v-for="(opt, i) in element.options ?? []"
          :key="i"
          class="flex items-center gap-2"
        >
          <input
            :value="opt"
            @input="updateOption(i, ($event.target as HTMLInputElement).value)"
            class="flex-1 min-w-0 border border-slate-200 dark:border-white/[0.07] rounded-lg px-3 py-1.5 text-sm text-slate-900 dark:text-white bg-white dark:bg-white/[0.03] focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500 focus:outline-none"
          />
          <button
            type="button"
            @click="removeOption(i)"
            class="p-1.5 text-slate-400 hover:text-rose-600 hover:bg-rose-50 dark:text-white/40 dark:hover:text-rose-400 dark:hover:bg-rose-500/10 rounded-lg"
            :aria-label="'Remove option ' + (i + 1)"
          >
            <Trash2 class="h-3.5 w-3.5" />
          </button>
        </div>
        <button
          type="button"
          @click="addOption"
          class="w-full py-1.5 text-[12px] font-medium text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-500/10 hover:bg-indigo-100 dark:hover:bg-indigo-500/20 rounded-lg transition-colors"
          style="transition-timing-function: cubic-bezier(0.16, 1, 0.3, 1)"
        >
          + Add option
        </button>
      </div>
    </FieldGroup>

    <details class="group border border-slate-200 dark:border-white/[0.07] rounded-lg">
      <summary class="flex items-center justify-between cursor-pointer px-3 py-2.5 list-none">
        <span class="text-[11px] font-semibold text-slate-500 dark:text-white/40 uppercase tracking-wider">
          Visibility rules
        </span>
        <ChevronDown
          class="h-3.5 w-3.5 text-slate-400 dark:text-white/40 group-open:rotate-180 transition-transform"
        />
      </summary>
      <div class="px-3 pb-3 pt-1 text-[12px] text-slate-500 dark:text-white/40 leading-relaxed">
        Show this field only when another field (in this step or earlier steps) matches a
        condition.
      </div>
    </details>
  </div>
</template>

<style scoped>
.ms-fade-up {
  animation: ms-fade-up 0.35s cubic-bezier(0.16, 1, 0.3, 1) both;
}
@keyframes ms-fade-up {
  from {
    opacity: 0;
    transform: translateY(6px);
  }
  to {
    opacity: 1;
    transform: none;
  }
}
@media (prefers-reduced-motion: reduce) {
  .ms-fade-up {
    animation: none;
  }
}

summary::-webkit-details-marker {
  display: none;
}
</style>
