import type { FormStep, MultiStepElement } from '../../../stores/multistepForm'

export type MultiStepFramework = 'vue' | 'react' | 'angular'

export interface GeneratedCode {
  filename: string
  code: string
}

interface FieldDescriptor {
  key: string
  type: MultiStepElement['type']
  label: string
  placeholder: string
  required: boolean
  options: string[]
}

interface StepDescriptor {
  title: string
  description: string
  fields: FieldDescriptor[]
}

function slug(s: string): string {
  return (s || '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_|_$/g, '')
}

function describeFields(steps: FormStep[]): StepDescriptor[] {
  const usedKeys = new Set<string>()
  return steps.map(s => ({
    title: s.title,
    description: s.description,
    fields: s.elements.map(e => {
      let key = slug(e.label) || `field_${Math.random().toString(36).slice(2, 6)}`
      let suffix = 1
      while (usedKeys.has(key)) {
        suffix++
        key = `${slug(e.label) || 'field'}_${suffix}`
      }
      usedKeys.add(key)
      return {
        key,
        type: e.type,
        label: e.label,
        placeholder: e.placeholder ?? '',
        required: !!e.required,
        options: e.options ?? [],
      }
    }),
  }))
}


// ──────────────────────────────────────────────────────────────────────────
// Vue 3 — Composition API + <script setup> + Tailwind
// ──────────────────────────────────────────────────────────────────────────

function generateVue(steps: StepDescriptor[]): string {
  const stepsLiteral = JSON.stringify(steps, null, 2)

  return `<!--
  Generated by FormAI — Multi-step form
  Stack: Vue 3 + <script setup> + TypeScript + Tailwind CSS
  Drop into any Vue 3 + Tailwind project. No external runtime required.
-->
<script setup lang="ts">
import { ref, computed } from 'vue'

interface Field {
  key: string
  type: string
  label: string
  placeholder: string
  required: boolean
  options: string[]
}

interface Step {
  title: string
  description: string
  fields: Field[]
}

const steps: Step[] = ${stepsLiteral}

const stepIndex = ref(0)
const formData = ref<Record<string, unknown>>({})
const completed = ref(false)
const showErrors = ref(false)

const currentStep = computed(() => steps[stepIndex.value])
const isFirst = computed(() => stepIndex.value === 0)
const isLast = computed(() => stepIndex.value === steps.length - 1)
const progress = computed(() => ((stepIndex.value + 1) / steps.length) * 100)

function isFieldFilled(field: Field): boolean {
  const value = formData.value[field.key]
  if (field.type === 'checkbox') return value === true
  if (field.type === 'otp') return typeof value === 'string' && value.length === 6
  return value !== undefined && value !== null && String(value).trim() !== ''
}

function stepValid(step: Step): boolean {
  return step.fields.every(f => !f.required || isFieldFilled(f))
}

function next() {
  if (!stepValid(currentStep.value)) {
    showErrors.value = true
    return
  }
  showErrors.value = false
  if (isLast.value) {
    submit()
  } else {
    stepIndex.value++
  }
}

function back() {
  if (!isFirst.value) {
    stepIndex.value--
    showErrors.value = false
  }
}

async function submit() {
  // TODO: replace with your real submit endpoint.
  // await fetch('/api/forms/${slug(steps[0]?.title || 'submission')}', { method: 'POST', body: JSON.stringify(formData.value) })
  completed.value = true
}

function setOtpDigit(field: Field, index: number, value: string) {
  const digit = value.replace(/\\D/g, '').slice(0, 1)
  const current = String(formData.value[field.key] ?? '')
  const next = current.padEnd(6, ' ').split('')
  next[index] = digit || ' '
  formData.value[field.key] = next.join('').replace(/\\s/g, '')
}

function reset() {
  stepIndex.value = 0
  formData.value = {}
  completed.value = false
  showErrors.value = false
}
<\/script>

<template>
  <div class="mx-auto w-full max-w-xl p-6">
    <!-- Progress bar -->
    <div class="mb-6">
      <div class="h-1 rounded-full bg-slate-200 overflow-hidden">
        <div
          class="h-full bg-indigo-500 transition-all duration-500"
          :style="{ width: progress + '%' }"
        />
      </div>
      <p class="mt-2 text-xs text-slate-500 tabular-nums">
        Step {{ stepIndex + 1 }} of {{ steps.length }}
      </p>
    </div>

    <!-- Completion -->
    <div
      v-if="completed"
      class="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center"
    >
      <h1 class="text-2xl font-bold text-slate-900 mb-2">All done!</h1>
      <p class="text-sm text-slate-600 mb-6">Your responses have been submitted.</p>
      <button
        type="button"
        @click="reset"
        class="px-4 py-2 rounded-lg text-sm font-semibold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50"
      >
        Start over
      </button>
    </div>

    <!-- Active step -->
    <form v-else @submit.prevent="next" class="rounded-2xl border border-slate-200 bg-white p-8">
      <h1 class="text-2xl font-bold text-slate-900">{{ currentStep.title }}</h1>
      <p v-if="currentStep.description" class="mt-1 text-sm text-slate-500">
        {{ currentStep.description }}
      </p>

      <div class="mt-6 space-y-4">
        <div v-for="field in currentStep.fields" :key="field.key">
          <label class="block text-sm font-semibold text-slate-700 mb-1.5">
            {{ field.label }}
            <span v-if="field.required" class="text-rose-500" aria-hidden="true">*</span>
          </label>

          <!-- text/email/number/phone/date -->
          <input
            v-if="['text', 'email', 'phone', 'number', 'date', 'url'].includes(field.type)"
            v-model="formData[field.key]"
            :type="field.type === 'phone' ? 'tel' : field.type"
            :placeholder="field.placeholder"
            :required="field.required"
            class="w-full px-3 py-2 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 outline-none"
          />

          <!-- textarea -->
          <textarea
            v-else-if="field.type === 'textarea'"
            v-model="formData[field.key]"
            :placeholder="field.placeholder"
            :required="field.required"
            rows="3"
            class="w-full px-3 py-2 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 outline-none resize-none"
          />

          <!-- otp -->
          <div v-else-if="field.type === 'otp'" class="flex gap-2" dir="ltr">
            <input
              v-for="i in 6"
              :key="i"
              :value="String(formData[field.key] ?? '').charAt(i - 1)"
              @input="(e) => setOtpDigit(field, i - 1, (e.target as HTMLInputElement).value)"
              maxlength="1"
              inputmode="numeric"
              class="w-11 h-12 text-center text-lg font-mono rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 outline-none"
            />
          </div>

          <!-- select -->
          <select
            v-else-if="field.type === 'select'"
            v-model="formData[field.key]"
            :required="field.required"
            class="w-full px-3 py-2 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 outline-none bg-white"
          >
            <option value="">Select…</option>
            <option v-for="opt in field.options" :key="opt" :value="opt">{{ opt }}</option>
          </select>

          <!-- radio -->
          <div v-else-if="field.type === 'radio'" class="space-y-2">
            <label
              v-for="opt in field.options"
              :key="opt"
              class="flex items-center gap-3 p-3 rounded-lg border border-slate-200 hover:border-indigo-300 cursor-pointer"
            >
              <input
                v-model="formData[field.key]"
                :name="field.key"
                :value="opt"
                type="radio"
                class="text-indigo-600"
                :required="field.required"
              />
              <span class="text-sm text-slate-700">{{ opt }}</span>
            </label>
          </div>

          <!-- checkbox -->
          <label
            v-else-if="field.type === 'checkbox'"
            class="flex items-start gap-3 p-3 rounded-lg border border-slate-200 cursor-pointer"
          >
            <input
              v-model="formData[field.key]"
              type="checkbox"
              class="mt-0.5 text-indigo-600 rounded"
              :required="field.required"
            />
            <span class="text-sm text-slate-700">{{ field.label }}</span>
          </label>

          <!-- file -->
          <input
            v-else-if="field.type === 'file'"
            type="file"
            @change="(e) => (formData[field.key] = (e.target as HTMLInputElement).files?.[0])"
            :required="field.required"
            class="w-full text-sm text-slate-700"
          />

          <!-- inline error -->
          <p
            v-if="showErrors && field.required && !isFieldFilled(field)"
            class="mt-1.5 text-xs text-rose-600"
          >
            This field is required.
          </p>
        </div>
      </div>

      <div class="mt-8 flex items-center justify-between gap-3">
        <button
          type="button"
          @click="back"
          :disabled="isFirst"
          class="px-4 py-2 rounded-lg text-sm font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 disabled:opacity-30 disabled:pointer-events-none"
        >
          Back
        </button>
        <button
          type="submit"
          class="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 shadow-lg shadow-indigo-500/25"
        >
          {{ isLast ? 'Submit' : 'Continue' }}
        </button>
      </div>
    </form>
  </div>
</template>
`
}

// ──────────────────────────────────────────────────────────────────────────
// React 18+ — functional component + hooks + Tailwind
// ──────────────────────────────────────────────────────────────────────────

function generateReact(steps: StepDescriptor[]): string {
  const stepsLiteral = JSON.stringify(steps, null, 2)
  return `// Generated by FormAI — Multi-step form
// Stack: React 18+ + TypeScript + Tailwind CSS
// Drop into any React + Tailwind project. No external runtime required.
import { useMemo, useState, type ChangeEvent } from 'react'

interface Field {
  key: string
  type: string
  label: string
  placeholder: string
  required: boolean
  options: string[]
}

interface Step {
  title: string
  description: string
  fields: Field[]
}

const steps: Step[] = ${stepsLiteral}

type FormState = Record<string, unknown>

function isFilled(field: Field, value: unknown): boolean {
  if (field.type === 'checkbox') return value === true
  if (field.type === 'otp') return typeof value === 'string' && value.length === 6
  return value !== undefined && value !== null && String(value).trim() !== ''
}

export default function MultiStepForm() {
  const [stepIndex, setStepIndex] = useState(0)
  const [form, setForm] = useState<FormState>({})
  const [done, setDone] = useState(false)
  const [showErrors, setShowErrors] = useState(false)

  const step = steps[stepIndex]
  const isFirst = stepIndex === 0
  const isLast = stepIndex === steps.length - 1
  const progress = useMemo(() => ((stepIndex + 1) / steps.length) * 100, [stepIndex])

  function setField(key: string, value: unknown) {
    setForm((prev) => ({ ...prev, [key]: value }))
  }

  function validateStep(): boolean {
    return step.fields.every((f) => !f.required || isFilled(f, form[f.key]))
  }

  async function submit() {
    // TODO: replace with your real submit endpoint.
    // await fetch('/api/forms/submission', { method: 'POST', body: JSON.stringify(form) })
    setDone(true)
  }

  function next() {
    if (!validateStep()) {
      setShowErrors(true)
      return
    }
    setShowErrors(false)
    if (isLast) submit()
    else setStepIndex((i) => i + 1)
  }

  function back() {
    if (!isFirst) {
      setStepIndex((i) => i - 1)
      setShowErrors(false)
    }
  }

  function setOtpDigit(field: Field, index: number, value: string) {
    const digit = value.replace(/\\D/g, '').slice(0, 1)
    const current = String(form[field.key] ?? '').padEnd(6, ' ').split('')
    current[index] = digit || ' '
    setField(field.key, current.join('').replace(/\\s/g, ''))
  }

  if (done) {
    return (
      <div className="mx-auto w-full max-w-xl p-6">
        <div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center">
          <h1 className="text-2xl font-bold text-slate-900 mb-2">All done!</h1>
          <p className="text-sm text-slate-600 mb-6">Your responses have been submitted.</p>
          <button
            type="button"
            onClick={() => {
              setStepIndex(0)
              setForm({})
              setDone(false)
              setShowErrors(false)
            }}
            className="px-4 py-2 rounded-lg text-sm font-semibold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50"
          >
            Start over
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="mx-auto w-full max-w-xl p-6">
      <div className="mb-6">
        <div className="h-1 rounded-full bg-slate-200 overflow-hidden">
          <div
            className="h-full bg-indigo-500 transition-all duration-500"
            style={{ width: \`\${progress}%\` }}
          />
        </div>
        <p className="mt-2 text-xs text-slate-500 tabular-nums">
          Step {stepIndex + 1} of {steps.length}
        </p>
      </div>

      <form
        onSubmit={(e) => {
          e.preventDefault()
          next()
        }}
        className="rounded-2xl border border-slate-200 bg-white p-8"
      >
        <h1 className="text-2xl font-bold text-slate-900">{step.title}</h1>
        {step.description && <p className="mt-1 text-sm text-slate-500">{step.description}</p>}

        <div className="mt-6 space-y-4">
          {step.fields.map((field) => {
            const value = form[field.key]
            const error = showErrors && field.required && !isFilled(field, value)
            const baseInput =
              'w-full px-3 py-2 rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 outline-none'

            return (
              <div key={field.key}>
                <label className="block text-sm font-semibold text-slate-700 mb-1.5">
                  {field.label}
                  {field.required && <span className="text-rose-500" aria-hidden="true">*</span>}
                </label>

                {['text', 'email', 'phone', 'number', 'date', 'url'].includes(field.type) && (
                  <input
                    type={field.type === 'phone' ? 'tel' : field.type}
                    value={(value as string) ?? ''}
                    onChange={(e) => setField(field.key, e.target.value)}
                    placeholder={field.placeholder}
                    required={field.required}
                    className={baseInput}
                  />
                )}

                {field.type === 'textarea' && (
                  <textarea
                    value={(value as string) ?? ''}
                    onChange={(e) => setField(field.key, e.target.value)}
                    placeholder={field.placeholder}
                    required={field.required}
                    rows={3}
                    className={\`\${baseInput} resize-none\`}
                  />
                )}

                {field.type === 'otp' && (
                  <div className="flex gap-2" dir="ltr">
                    {[0, 1, 2, 3, 4, 5].map((i) => (
                      <input
                        key={i}
                        value={(String(value ?? '')).charAt(i)}
                        onChange={(e: ChangeEvent<HTMLInputElement>) =>
                          setOtpDigit(field, i, e.target.value)
                        }
                        maxLength={1}
                        inputMode="numeric"
                        className="w-11 h-12 text-center text-lg font-mono rounded-lg border border-slate-200 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20 outline-none"
                      />
                    ))}
                  </div>
                )}

                {field.type === 'select' && (
                  <select
                    value={(value as string) ?? ''}
                    onChange={(e) => setField(field.key, e.target.value)}
                    required={field.required}
                    className={\`\${baseInput} bg-white\`}
                  >
                    <option value="">Select…</option>
                    {field.options.map((o) => (
                      <option key={o} value={o}>{o}</option>
                    ))}
                  </select>
                )}

                {field.type === 'radio' && (
                  <div className="space-y-2">
                    {field.options.map((o) => (
                      <label
                        key={o}
                        className="flex items-center gap-3 p-3 rounded-lg border border-slate-200 hover:border-indigo-300 cursor-pointer"
                      >
                        <input
                          type="radio"
                          name={field.key}
                          value={o}
                          checked={value === o}
                          onChange={() => setField(field.key, o)}
                          required={field.required}
                          className="text-indigo-600"
                        />
                        <span className="text-sm text-slate-700">{o}</span>
                      </label>
                    ))}
                  </div>
                )}

                {field.type === 'checkbox' && (
                  <label className="flex items-start gap-3 p-3 rounded-lg border border-slate-200 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={value === true}
                      onChange={(e) => setField(field.key, e.target.checked)}
                      required={field.required}
                      className="mt-0.5 text-indigo-600 rounded"
                    />
                    <span className="text-sm text-slate-700">{field.label}</span>
                  </label>
                )}

                {field.type === 'file' && (
                  <input
                    type="file"
                    onChange={(e) => setField(field.key, e.target.files?.[0])}
                    required={field.required}
                    className="w-full text-sm text-slate-700"
                  />
                )}

                {error && <p className="mt-1.5 text-xs text-rose-600">This field is required.</p>}
              </div>
            )
          })}
        </div>

        <div className="mt-8 flex items-center justify-between gap-3">
          <button
            type="button"
            onClick={back}
            disabled={isFirst}
            className="px-4 py-2 rounded-lg text-sm font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 disabled:opacity-30 disabled:pointer-events-none"
          >
            Back
          </button>
          <button
            type="submit"
            className="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 shadow-lg shadow-indigo-500/25"
          >
            {isLast ? 'Submit' : 'Continue'}
          </button>
        </div>
      </form>
    </div>
  )
}
`
}

// ──────────────────────────────────────────────────────────────────────────
// Angular 17+ — standalone + signals + Tailwind
// ──────────────────────────────────────────────────────────────────────────

function generateAngular(steps: StepDescriptor[]): string {
  const stepsLiteral = JSON.stringify(steps, null, 2)
  return `// Generated by FormAI — Multi-step form
// Stack: Angular 17+ standalone component + signals + Tailwind CSS
// Drop into any Angular 17+ project (zoneless-friendly).
import { Component, signal, computed } from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'

interface Field {
  key: string
  type: string
  label: string
  placeholder: string
  required: boolean
  options: string[]
}

interface Step {
  title: string
  description: string
  fields: Field[]
}

const STEPS: Step[] = ${stepsLiteral}

@Component({
  selector: 'app-multi-step-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: \`
    <div class="mx-auto w-full max-w-xl p-6">
      <div class="mb-6">
        <div class="h-1 rounded-full bg-slate-200 overflow-hidden">
          <div class="h-full bg-indigo-500 transition-all duration-500"
               [style.width.%]="progress()"></div>
        </div>
        <p class="mt-2 text-xs text-slate-500 tabular-nums">
          Step {{ stepIndex() + 1 }} of {{ steps.length }}
        </p>
      </div>

      <ng-container *ngIf="!completed(); else doneTpl">
        <form (submit)="$event.preventDefault(); next()"
              class="rounded-2xl border border-slate-200 bg-white p-8">
          <h1 class="text-2xl font-bold text-slate-900">{{ currentStep().title }}</h1>
          <p *ngIf="currentStep().description" class="mt-1 text-sm text-slate-500">
            {{ currentStep().description }}
          </p>

          <div class="mt-6 space-y-4">
            <div *ngFor="let field of currentStep().fields">
              <label class="block text-sm font-semibold text-slate-700 mb-1.5">
                {{ field.label }}
                <span *ngIf="field.required" class="text-rose-500" aria-hidden="true">*</span>
              </label>

              <input *ngIf="textTypes.includes(field.type)"
                     [type]="field.type === 'phone' ? 'tel' : field.type"
                     [placeholder]="field.placeholder"
                     [required]="field.required"
                     [(ngModel)]="form[field.key]" [name]="field.key"
                     class="w-full px-3 py-2 rounded-lg border border-slate-200 focus:border-indigo-500 outline-none" />

              <textarea *ngIf="field.type === 'textarea'"
                        [placeholder]="field.placeholder"
                        [required]="field.required"
                        rows="3"
                        [(ngModel)]="form[field.key]" [name]="field.key"
                        class="w-full px-3 py-2 rounded-lg border border-slate-200 focus:border-indigo-500 outline-none resize-none"></textarea>

              <select *ngIf="field.type === 'select'"
                      [required]="field.required"
                      [(ngModel)]="form[field.key]" [name]="field.key"
                      class="w-full px-3 py-2 rounded-lg border border-slate-200 focus:border-indigo-500 outline-none bg-white">
                <option value="">Select…</option>
                <option *ngFor="let o of field.options" [value]="o">{{ o }}</option>
              </select>

              <div *ngIf="field.type === 'radio'" class="space-y-2">
                <label *ngFor="let o of field.options"
                       class="flex items-center gap-3 p-3 rounded-lg border border-slate-200 hover:border-indigo-300 cursor-pointer">
                  <input type="radio" [name]="field.key" [value]="o"
                         [(ngModel)]="form[field.key]" [required]="field.required"
                         class="text-indigo-600" />
                  <span class="text-sm text-slate-700">{{ o }}</span>
                </label>
              </div>

              <label *ngIf="field.type === 'checkbox'"
                     class="flex items-start gap-3 p-3 rounded-lg border border-slate-200 cursor-pointer">
                <input type="checkbox" [(ngModel)]="form[field.key]"
                       [name]="field.key" [required]="field.required"
                       class="mt-0.5 text-indigo-600 rounded" />
                <span class="text-sm text-slate-700">{{ field.label }}</span>
              </label>

              <input *ngIf="field.type === 'file'" type="file"
                     (change)="form[field.key] = $any($event.target).files?.[0]"
                     [required]="field.required"
                     class="w-full text-sm text-slate-700" />

              <p *ngIf="showErrors() && field.required && !isFilled(field)"
                 class="mt-1.5 text-xs text-rose-600">This field is required.</p>
            </div>
          </div>

          <div class="mt-8 flex items-center justify-between gap-3">
            <button type="button" (click)="back()" [disabled]="isFirst()"
                    class="px-4 py-2 rounded-lg text-sm font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 disabled:opacity-30 disabled:pointer-events-none">Back</button>
            <button type="submit"
                    class="px-4 py-2 rounded-lg text-sm font-semibold text-white bg-indigo-600 hover:bg-indigo-700 shadow-lg shadow-indigo-500/25">
              {{ isLast() ? 'Submit' : 'Continue' }}
            </button>
          </div>
        </form>
      </ng-container>

      <ng-template #doneTpl>
        <div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-8 text-center">
          <h1 class="text-2xl font-bold text-slate-900 mb-2">All done!</h1>
          <p class="text-sm text-slate-600 mb-6">Your responses have been submitted.</p>
          <button type="button" (click)="reset()"
                  class="px-4 py-2 rounded-lg text-sm font-semibold text-slate-700 bg-white border border-slate-200 hover:bg-slate-50">Start over</button>
        </div>
      </ng-template>
    </div>
  \`,
})
export class MultiStepFormComponent {
  steps = STEPS
  textTypes = ['text', 'email', 'phone', 'number', 'date', 'url']
  stepIndex = signal(0)
  completed = signal(false)
  showErrors = signal(false)
  form: Record<string, unknown> = {}

  currentStep = computed(() => this.steps[this.stepIndex()])
  isFirst = computed(() => this.stepIndex() === 0)
  isLast = computed(() => this.stepIndex() === this.steps.length - 1)
  progress = computed(() => ((this.stepIndex() + 1) / this.steps.length) * 100)

  isFilled(field: Field): boolean {
    const value = this.form[field.key]
    if (field.type === 'checkbox') return value === true
    if (field.type === 'otp') return typeof value === 'string' && value.length === 6
    return value !== undefined && value !== null && String(value).trim() !== ''
  }

  validate(): boolean {
    return this.currentStep().fields.every((f) => !f.required || this.isFilled(f))
  }

  next() {
    if (!this.validate()) {
      this.showErrors.set(true)
      return
    }
    this.showErrors.set(false)
    if (this.isLast()) {
      this.submit()
    } else {
      this.stepIndex.update((i) => i + 1)
    }
  }

  back() {
    if (!this.isFirst()) {
      this.stepIndex.update((i) => i - 1)
      this.showErrors.set(false)
    }
  }

  async submit() {
    // TODO: replace with your real submit endpoint.
    // await fetch('/api/forms/submission', { method: 'POST', body: JSON.stringify(this.form) })
    this.completed.set(true)
  }

  reset() {
    this.stepIndex.set(0)
    this.form = {}
    this.completed.set(false)
    this.showErrors.set(false)
  }
}
`
}

export function generateMultiStepCode(
  framework: MultiStepFramework,
  steps: FormStep[]
): GeneratedCode {
  const descriptors = describeFields(steps)

  if (framework === 'vue') {
    return { filename: 'MultiStepForm.vue', code: generateVue(descriptors) }
  }
  if (framework === 'react') {
    return { filename: 'MultiStepForm.tsx', code: generateReact(descriptors) }
  }
  return {
    filename: 'multi-step-form.component.ts',
    code: generateAngular(descriptors),
  }
}

// ──────────────────────────────────────────────────────────────────────────
// AI prompt — a strict brief an LLM can execute, not a vague request.
// ──────────────────────────────────────────────────────────────────────────

const FRAMEWORK_BRIEF: Record<MultiStepFramework, string> = {
  vue: `Vue 3 with <script setup lang="ts">, ref/computed, no Pinia (component-local state). Style with Tailwind CSS. Use v-model on inputs. Single-file component.`,
  react: `React 18+ functional component with TypeScript and hooks (useState, useMemo). Style with Tailwind CSS. Default export. No external state library.`,
  angular: `Angular 17+ standalone component with signals (signal/computed) and FormsModule [(ngModel)]. Style with Tailwind CSS. Importable directly.`,
}

function fieldLine(f: FieldDescriptor): string {
  const pieces = [`- ${f.label} (\`${f.key}\`, type: ${f.type})`]
  if (f.required) pieces.push('required')
  if (f.placeholder) pieces.push(`placeholder: "${f.placeholder}"`)
  if (f.options.length) pieces.push(`options: [${f.options.map(o => `"${o}"`).join(', ')}]`)
  return pieces.join(' · ')
}

export function generateMultiStepPrompt(
  framework: MultiStepFramework,
  steps: FormStep[]
): string {
  const descriptors = describeFields(steps)
  const stepBlocks = descriptors
    .map(
      (s, i) =>
        `### Step ${i + 1}: ${s.title}\n` +
        (s.description ? `_${s.description}_\n` : '') +
        s.fields.map(fieldLine).join('\n')
    )
    .join('\n\n')

  return `You are a senior ${framework} engineer. Build a production-ready multi-step form using the spec below.

## Stack
${FRAMEWORK_BRIEF[framework]}

## Steps & fields

${stepBlocks}

## Behavior

1. Render exactly one step at a time. The user advances with **Continue** and goes back with **Back**.
2. The Continue button on the last step is labeled **Submit** and posts \`form\` as JSON to a placeholder \`/api/forms/submission\` endpoint, then shows a success state with a "Start over" action.
3. Validate per-step before advancing: every \`required\` field must have a non-empty value. For checkbox-type fields, "non-empty" means checked (\`true\`). For OTP-type fields, "non-empty" means exactly 6 digits.
4. Show inline error messages only after the user attempts to advance ("This field is required.").
5. Maintain a single \`form\` state object keyed by each field's \`key\` (snake_case generated from the label).
6. Render a slim progress bar at the top showing \`(stepIndex + 1) / totalSteps\` and a small "Step N of M" counter.
7. Disable **Back** on the first step. Reset \`showErrors\` whenever the active step changes.
${
  steps.some(s => s.elements.some(e => e.type === 'otp'))
    ? `8. For OTP fields, render six 1-character inputs side-by-side, auto-advance focus to the next box on input, and combine them into a single string in \`form[key]\`.\n`
    : ''
}

## Field rendering

| type | element |
|---|---|
| text / email / phone / number / date / url | \`<input>\` with the matching HTML type (use \`tel\` for phone) |
| textarea | \`<textarea rows=3>\` |
| select | \`<select>\` with options + a default "Select…" placeholder |
| radio | stacked label cards with one \`<input type="radio">\` each |
| checkbox | single label card with a checkbox; the field's label doubles as the prompt |
| otp | six 1-char numeric inputs side-by-side |
| file | \`<input type="file">\` storing the first selected File in state |

## Styling

Use Tailwind utility classes only. Light theme. Primary accent: \`indigo-500\`/\`indigo-600\`. Rounded corners (\`rounded-lg\`/\`rounded-2xl\`), subtle borders (\`border-slate-200\`), generous padding (\`p-6\`/\`p-8\`). Buttons: \`bg-indigo-600 text-white\` for the primary action, \`bg-slate-100\` for Back. Inputs use \`focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500/20\`.

## Accessibility

- Each field has an associated \`<label>\` (use \`htmlFor\`/\`for\` or a wrapping label).
- The required marker (\`*\`) is decorative — add \`aria-hidden="true"\`.
- Buttons are real \`<button type="button"/submit>\` elements; the form submits on Enter.
- Disabled state on Back uses \`disabled\` and \`disabled:opacity-30 disabled:pointer-events-none\`.

## Output

Return a single self-contained component file with no external dependencies beyond the framework runtime and Tailwind. Do not split across multiple files. Do not add a router or state library.`
}
